[tool.poetry]
name = "alinka-pyside"
version = "0.1.0"
description = "Aplication for Supporting Center for Children"
authors = ["CodeForPoznań <hello@codeforpoznan.pl>"]

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.2"
pydantic = "^1.10.2"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
black = "^22.10.0"
flake8 = "^5.0.4"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
indent='    '
known_first_party = "app"
line_length = 120
multi_line_output = 3
use_parentheses = true
overwrite_in_place = true

[tool.pytest.ini_options]
pythonpath = ["app"]